// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:terminal_studio/src/core/record/settings_record.dart';
import 'package:terminal_studio/src/core/record/ssh_host_record.dart';
import 'package:terminal_studio/src/core/record/ssh_key_record.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SSHHostRecordAdapter());
    registerAdapter(SSHKeyRecordAdapter());
    registerAdapter(SettingsRecordAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SSHHostRecordAdapter());
    registerAdapter(SSHKeyRecordAdapter());
    registerAdapter(SettingsRecordAdapter());
  }
}
